name: Issues Event Info
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Display event info
        run: |
            echo "Event Name: ${{ github.event_name }}"
            echo "=================================="
            echo "Event Details: ${{ toJson(github.event) }}"
            echo "=================================="